### PR TITLE
Seperate out importing code

### PR DESCRIPTION
**Pull request by bagel897**
I'm working on creating a plugin for autoimport for pylsp and would find it useful if we could get a list of all possible imports without formatting the file so we can implement autoimport when you autocomplete, not on formatting. I split off the relevant parts off to the SourceCodeBase class and exposed two new functions - find_package and get_all_packages. I don't need find_package, but it was largely implemented and could lead to a better solution if get_all_packages doesn't work.
## Checklist
* [ ] Add search for modules to get_all_packages
* [ ] Implement caching for get_all_packages.
* [ ] Add test cases to all the changes you introduce
* [ ] Update the documentation for the changes

### CODE REVIEW

**Comment by lyz-code** [comment]
Thanks @bageljrkhanofemus , thanks for starting the contribution.

As far as I can see right now it looks good. Can't wait to see it finished :)

Maybe you're interested in https://github.com/lyz-code/autoimport/issues/39 too

**Comment by bageljrkhanofemus** [comment]
So a little update, I'm working on trying to find out what modules are installed, and wanted to see how rope handles this part. So it turns out Rope has their own implementation (with caching and a similar featureset) [here](https://github.com/python-rope/rope/blob/master/rope/contrib/autoimport.py). 
1. It has the same issue, it doesn't automatically find standard library modules
2. It can't handle "Resources" outside of the ropeproject

However, it can determine the python path(s) of the current project, which will make that part easier. 
I think the best approach is to de-duplicate the work, use the rope autoimport code as a backend (if/once I can make it detect standard modules) and replace the actually finding imports here with that.

**Comment by lyz-code** [comment]
Hi @bageljrkhanofemus I've got some doubts, please bear with me as it's been some time since I dove into `autoimport`s code:

* I haven't used LSP before, why do you need to run autoimport at autocomplete? will that update the file when you try to autocomplete a variable?
* I've skimmed through the code of the rope project, it looks good, but beside delegating in them the code I don't see the benefits of using their backend. Can you share your thoughts on the strong points of this approach?
* As far as I remember, we currently know what modules are installed, what is the problem here?
* I don't see any installation guide of rope, would it mean that we add them as a library dependency? or will the users need to install additional software to make `autoimport` work?

What I do see is a great idea is:

* Build a cache of the installed packages and the project objects.
* Build a tree of the project files so that we can implement [relative imports](https://github.com/lyz-code/autoimport/issues/75)

I'm very excited of your ideas and implementation, please keep me updated

**Comment by bageljrkhanofemus** [comment]
## Autoimport while writing code
image
So say I'm writing code, and want to include typing's List class in my code. The current workflow is

1. I type out the List manually
2. I get a undefined name error
3. I save, formatting the code, triggering a run of autoimport (automatically via pylsp-autoimport or manually via autoimport)
This has a couple of issues for an LSP implementation
1. Its inefficient, since we're already running flake8 and are now duplicating the check
2. It has formatting issues, since autoimport messes up the imports somewhat 
3. Its import sorting is redundant when isort is being run on the same file
A better workflow would be to
1. Determine what modules are available (possibly with caching)
2. When the user is typing, they'll see the option for autocompleting List, with the description that it imports from typing
3. When the user selects it, it finds out what line of code it needs to place the import statement and does so, without saving the file.
## How do I do that
Autoimport does store a list of all available imports for the project, typing, and common statements. However, for a PYTHONPATH module search, it uses importlib to determine which python files we can use. Since we can't assume autoimport is running from the same path as the project its working on, this is unsatsifactory for 2 reasons.

1. It may have issues if autoimport and the project have different modules available, which will almost certainly be the case
2. It can't give us available imports ahead of time (as far as I can tell)

So what the code needs to do is
1. find the pythonpath of the _project_ (Rope does this, but I'm not sure how)
2. find the list of modules in each python path and watch for changes (WIP)
3. Cache the list of available imports for each modules (both your extract package objects and rope can do this)
4. Return the correct import for the given name for postfixing, or all imports for autocompletion
5. cache the result (rope can mostly do this)

So rope has a couple of advantages for embedding in _pylsp_, namely:
1. rope is already an optional dependency of pylsp
2. rope is designed to be embedded and has been embedded in pylsp 
3. it has the ability to watch for changes in the project (which can probably be expanded to external modules)
4. it has less dependencies than autoimport (it just depends on itself and python and its installable via pip)
5. It has information on project files and their locations relative to each other (though I'm not sure if it uses that currently).
## Progress so far
I got rope to cache all the packages in my site-packages (though that was very slow)
image

**Comment by lyz-code** [comment]
Thanks for the explanation it was cristal clear. 

I see your point on the need of being able to run `autoimport` at autocompletion time, I'm thrilled to see the outcome of this PR, it looks like you're giving the package an awesome twist, thank you. 

I'm curious too to know how does rope manage the cache and how does it watch the changes in the pythonpath.

We currently find the PYTHONPATH with [pyprojroot](https://github.com/chendaniely/pyprojroot), I don't know if it can fulfill your needs. I wouldn't have any problem ditching it in favour of rope.

Thanks again :)

**Comment by bageljrkhanofemus** [comment]
While that is useful (especially since rope needs that anyway), it doesn't give us the full information
Our imports basically come from 2 sources
1. Items inside the project
 a) we can find the project location with pyprojectroot
 b) rope needs to know the project location
3. Items found from installed modules and python standard library which actually consists of multiple paths (IE: /usr/lib/python3.10, /usr/lib/python3.10/site-pacakges, local folders, venvs, etc).  Rope uses a configuration file and appends it to sys.path to get this

Rope manages a cache for the project itself, watches for changes and updates that accordingly (rope's codebase is larger so I haven't read through the whole thing yet) and it stores its cache in a .ropeproject folder. 
However, it's cache doesn't handle modules being removed/added.
I've got a basic layer where autoimport uses rope under the hood. It has a better module name parser and is faster at parsing the entire stdlib.  I'm working on how to store/update the data for external modules in a convenient manner.

**Comment by lyz-code** [comment]
I've given it a little bit of thought and this is what I came out with:

To make the autocompletion quicker, we could split the reading of cache and the update. So when we use the autocomplete it will only fetch items from the cache, and when it saves it updates the cache. Another option would be to only read the cache when saving and autocompleting, and have a daemon in another process that is monitoring the file changes and update the cache then. An alternative to rope's system could be using [inotify](https://askubuntu.com/questions/819265/bash-script-to-monitor-file-change-and-execute-command/819290#819290) to monitor the file changes.

Right now the vim's integration with Ale runs `autoimport` in a temp file in `tmp` so it's difficult to know what project does that file belong to. After seeing other integrations ([flakehell](https://github.com/dense-analysis/ale/blob/master/ale_linters/python/flakehell.vim), [pylint](https://github.com/dense-analysis/ale/blob/master/ale_linters/python/pylint.vim), [mypy](https://github.com/dense-analysis/ale/blob/master/ale_linters/python/mypy.vim)), there's a possibility to run ale with a `cwd` argument that specifies the project's root directory. So we can assume that we know the original file path.

**Comment by lyz-code** [comment]
One way of monitoring 4 could be by package manager hooks, I'm currently using PDM, and it looks like it's easy to write a plugin that updates the cache on package changes. I will add it as an optional feature so as not to force the users to use PDM

**Comment by lieryan** [comment]
Simplest way is to `path.stat()` and check for filesystem metadata ([stat_result](https://docs.python.org/3/library/os.html#os.stat_result)), specifically the `st_mtime` (modification time) and `st_size` (file size), and maybe the `st_ctime` (creation time) too. That's how Git quickly detects file changes.

It's not fool-proof, but it'll be much faster than any methods that reads off the file content like hashing the whole directory and it should work for the vast majority of the time. 

Compared to package manager hooks, it would not require modifying the virtualenv directory nor for the editor's plugin virtualenv to be the same as the project virtualenv.

Compared to inotify, saving file metadata would not require a deamon that needs to remain alive while the files/folder was being modified, so when using inotify, you will still need a way to find changes at startup since the daemon shuts down. inotify is faster than metadata scanning though, so for when you already have a persistent daemon (e.g. pylsp), inotify can be a good optimization.

**Comment by bageljrkhanofemus** [comment]
Woah that's smart, I'll add it to my code for updating packages. That's going to be way faster than hashing anything.

**Comment by lyz-code** [comment]
I'm so sad to hear that @bageljrkhanofemus , I completely understand though. Can you please add a link to your project so that if anyone want's to continue this initiative can take it as a reference?

**Comment by bageljrkhanofemus** [comment]
1. The rope project in docs/library.rst and accompanying docstrings. Ideally, this will be moved to RTD. 
2. This PR
3. https://github.com/python-lsp/python-lsp-server/pull/199

**Pull request closed without merging**
