### PR TITLE
Allow cli to accept directories

### PR DESCRIPTION
**Pull request by superDross**
Addresses the below issue:

https://github.com/lyz-code/autoimport/issues/141

This MR allows users to parse in a directory (or multiple directories and/or multiple files) and autoimport will recursively correct all python files in said directory.

## Checklist

* [x] Add test cases to all the changes you introduce
* [x] Update the documentation for the changes

### CODE REVIEW

**Review by lyz-code — APPROVED** [review]
Wonderful contribution, thank you so much :)

**Review by lyz-code — CHANGES_REQUESTED** [review]
I've just seen that the [CI didn't pass](https://github.com/lyz-code/autoimport/runs/4834423392?check_suite_focus=true), I've [corrected the pipeline hooks](https://github.com/lyz-code/autoimport/commit/d53bcfbf9b76bbd49f942c60cb2de54e3fb46503) in theory they should now appear when you make changes in the PR

**Comment by superDross** [comment]
I have managed to fix the mypy error, thanks for the guidance. Additionally the security stage was failing (this is also affecting `master` it seems). I have updated the packages via `pip-tools` which seems to resolve the issue.

A test was failing before my changes were added (I checked this by checking out `master` and executing the testsuite). The test is `test_config_path_argument`.

I have fixed this. The gist of the problem was that when parsing the config file via the cli `--config-file` the config dict appears as `{'tool': {'autoimport': {'common_statements': {...}}}}` opposed to the auto discovered config which looks like `{'common_statements': {...}}`.

The fix is part of a separate commit.

**Review by lyz-code — APPROVED** [review]
Superb job! thank you so much :)

**Pull request merged**
